"""add image options and quiz timer

Revision ID: 619ee6bde2c1
Revises: a86eb6b633b1
Create Date: 2025-11-13 06:44:31.290184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619ee6bde2c1'
down_revision = 'a86eb6b633b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('option_d')
        batch_op.drop_column('option_a')
        batch_op.drop_column('option_b')
        batch_op.drop_column('video_filename')
        batch_op.drop_column('option_c')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_c', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('option_b', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('option_a', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('option_d', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
