"""rename selected_choice_id to choice_id

Revision ID: 778945dd8f3e
Revises: 619ee6bde2c1
Create Date: 2025-11-13 14:22:51.061806
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778945dd8f3e'
down_revision = '619ee6bde2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - fixed for SQLite ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        # Tambahkan kolom baru
        batch_op.add_column(sa.Column('choice_id', sa.Integer(), nullable=True))
        # Buat foreign key baru ke tabel choice
        batch_op.create_foreign_key('fk_answer_choice', 'choice', ['choice_id'], ['id'])
        # Hapus kolom lama
        batch_op.drop_column('selected_choice_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('qtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - fixed for SQLite ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtype', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.VARCHAR(length=10), nullable=True))
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_choice_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_answer_selected_choice', 'choice', ['selected_choice_id'], ['id'])
        batch_op.drop_column('choice_id')
    # ### end Alembic commands ###
